### ISSUE TITLE
speculative sampling 结果和target model输出结果不一致

### ISSUE THREAD

**Issue by lawo123** [feifeibear/LLMSpeculativeSampling#1]
作者你好，尝试跑了一下代码，请教您一个问题：speculative sampling 输出结果和target model的输出结果不一致，不知道您在运行的时候是否有这个问题？
![image](https://github.com/feifeibear/LLMSpeculativeSampling/assets/44777088/8b7c1ba6-2a66-4b0e-88c5-954d20631be0)

**Comment by feifeibear** [comment]
你这个问题比较典型
Speculative Sampling保证采样的概率**分布**一样，不是和auto-regressive sampling运行的输出完全一样。
你可以看readme里截图，如果用小模型是不能理解翻译任务的，用大模型和Speculative Sampling则可以。

**Comment by feifeibear** [comment]
> 了解了，感谢。请问这个解码可以直接使用在对话任务中吗？比如chatglm，会导致损失吗？ 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Jiarui Fang ***@***.***&gt; 发送时间: 2023年8月29日 17:29 收件人: feifeibear/LLMSpeculativeSampling ***@***.***&gt; 抄送: lawo123 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [feifeibear/LLMSpeculativeSampling] speculative sampling 结果和target model输出结果不一致 (Issue #1) 你这个问题比较典型 Speculative Sampling保证采样的概率分布一样，不是和auto-regressive sampling运行的输出完全一样。 你可以看readme里截图，如果用小模型是不能理解翻译任务的，用大模型和Speculative Sampling则可以。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不会的，和自回归完全等价。

**Comment by dearowen** [comment]
你好  想问下这套东西支持多batch吗？

**Comment by feifeibear** [comment]
> 你好 想问下这套东西支持多batch吗？

有待研究
