### ISSUE TITLE
Unable to Reproduce Results from README File

### ISSUE THREAD

**Issue by pppyb** [feifeibear/LLMSpeculativeSampling#30]
Hi,

Thank you very much for your work. However, I am having trouble reproducing the results from your paper. I set the benchmark to true and used the following command:

```bash
python main.py --input "The quick brown fox jumps over the lazy " --target_model_name bigscience/bloomz-7b1 --approx_model_name bigscience/bloom-560m
```

The generated results are as follows:

1. The BLOOM model is smaller than the LLaMA model, but the generation speed is much slower than the LLaMA model results in your README file. My GPU is an A100 80G.
2. This result is quite strange. It generates 0.81 tokens per second. AS_large, tokens/sec: 0.8131368569357317, 0.3566435311920941 sec generates 29 tokens.  https://github.com/feifeibear/LLMSpeculativeSampling/blob/1da363e9d2201663577aa2d90074853e5fda7812/main.py#L69C1-L70C1

<img width="1461" alt="image" src="https://github.com/user-attachments/assets/291cb449-d8ff-4422-b9af-b85a033c7b6a">

Could you please provide some guidance on what might be going wrong?

Thank you.

Best regards,
Yibo

**Comment by feifeibear** [comment]
When the sizes of two models are not significantly different, especially when you are using small models, it is suggested that the draft and approx model sizes in Sps should ideally differ by two orders of magnitude.

I also not obverse speedup on bloom 7B and 570m.

The code is designed to help you understand the principles of Sps, but in practice, there are many factors to consider for acceleration.
